//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentMaster
    {
        public System.Guid DepartmentId { get; set; }
        public string DepartmentDesc { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public System.Guid BranchID { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual DepartmentMaster DepartmentMaster1 { get; set; }
        public virtual DepartmentMaster DepartmentMaster2 { get; set; }
    }
}
