//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuMaster()
        {
            this.User_Authorization = new HashSet<User_Authorization>();
        }
    
        public System.Guid Id { get; set; }
        public string ControllerName { get; set; }
        public string MethodName { get; set; }
        public string Caption { get; set; }
        public int Order_by { get; set; }
        public bool IsActive { get; set; }
        public string Icon { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public bool IsDropDown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Authorization> User_Authorization { get; set; }
    }
}
