//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.Guid RoleId { get; set; }
        public bool StatusId { get; set; }
        public System.Guid BranchId { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual User_Roles User_Roles { get; set; }
    }
}
