//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid VisitorID { get; set; }
        public System.Guid VisitPurposeID { get; set; }
        public string CardNo { get; set; }
        public string Remarks { get; set; }
        public string EventName { get; set; }
        public string VisitFor { get; set; }
        public System.Guid DepartmentID { get; set; }
        public bool IsMannual { get; set; }
        public Nullable<System.DateTime> CheckIN { get; set; }
        public Nullable<System.DateTime> CheckOUT { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
    }
}
