//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VmsEntities : DbContext
    {
        public VmsEntities()
            : base("name=VmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BranchMaster> BranchMasters { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public virtual DbSet<MenuMaster> MenuMasters { get; set; }
        public virtual DbSet<User_Authorization> User_Authorization { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<ErrorLogMaster> ErrorLogMasters { get; set; }
        public virtual DbSet<VisitDetail> VisitDetails { get; set; }
        public virtual DbSet<VisitorMaster> VisitorMasters { get; set; }
        public virtual DbSet<VisitorStatu> VisitorStatus { get; set; }
        public virtual DbSet<VisitorType> VisitorTypes { get; set; }
        public virtual DbSet<VisitPurpose> VisitPurposes { get; set; }
    }
}
